import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { getAuth } from 'firebase-admin/auth';
initializeApp({credential: cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON))});
const db=getFirestore();
const s=await db.collection('orders').get();
let total=0,noUid=0;const sample=[];
s.forEach(d=>{const o=d.data();total++;if(!o.userId){noUid++;if(!o.orderNumber?.startsWith('test')&&sample.length<4)sample.push({id:d.id,keys:Object.keys(o)});}});
console.log({total,noUid});
console.log(JSON.stringify(sample,null,1));
const one=await db.collection('orders').doc('PHP-MU08HRNM').get();
const o=one.data();
console.log(JSON.stringify(Object.fromEntries(Object.entries(o).map(([k,v])=>[k,typeof v==='object'?'[obj]':v])),null,1));
