import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
initializeApp({credential: cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON))});
const db=getFirestore();
const s=await db.collection('orders').get();
let mixed=0,lower=0;
s.forEach(d=>{const e=d.data().customer?.email;if(!e)return;e===e.toLowerCase()?lower++:mixed++;});
console.log({lower,mixed});
const q=await db.collection('orders').where('customer.email','==','koberdean@icloud.com').get();
console.log('query by nested email hits:',q.size);
