import admin from 'firebase-admin';
admin.initializeApp({credential: admin.credential.cert(JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT_JSON))});
const db = admin.firestore();
const snap = await db.collection('orders').get();
const ms = (v)=> v?.toMillis?.() ?? (v?._seconds? v._seconds*1000 : (typeof v==='number'?v:(v?Date.parse(v):0)));
const dist={}; const rows=[];
snap.forEach(d=>{ const o=d.data(); const k=`${o.status}/${o.paymentStatus||'-'}`; dist[k]=(dist[k]||0)+1;
 rows.push({ref:o.orderRef||d.id,status:o.status,ps:o.paymentStatus,paidAt:ms(o.paidAt),created:ms(o.createdAt||o.orderDate),api:o.apiPaymentId||o.wallidPaymentId||o.paymentId,total:o.totalPrice,email:o.customerEmail||o.email,bankRef:o.bankReference||o.wallidReference||null}); });
console.log('count',rows.length); console.log(dist);
const unpaid = rows.filter(r=>!r.paidAt && !['shipped','delivered','paid','completed'].includes(r.status));
console.log('unpaid-ish', unpaid.length);
console.log(JSON.stringify(unpaid.sort((a,b)=>b.created-a.created).slice(0,25).map(r=>({ref:r.ref,s:r.status,ps:r.ps,api:r.api,total:r.total,ageH:((Date.now()-r.created)/3600e3).toFixed(1)})),null,1));
