/**
 * Sitemap policy ↔ route-tree consistency check.
 *
 * Guarantees that every route generated by TanStack Router file-based routing
 * is either:
 *   (a) excluded from the sitemap by policy (sitemap-policy.ts), OR
 *   (b) listed in KNOWN_PUBLIC_ROUTES (the canonical "should be in sitemap" set).
 *
 * If a new route file is added without updating either list, this test fails
 * with a clear pointer to the file to edit. Run with:
 *   bunx vitest run tests/sitemap-policy-consistency.test.ts
 */
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { exclusionReason, isIndexable } from "../src/lib/sitemap-policy";
import { KNOWN_PUBLIC_ROUTES } from "../src/lib/sitemap-audit.functions";

/**
 * Extract every public URL path declared in routeTree.gen.ts. We read the
 * `FileRoutesByTo` interface block, which lists each route exactly once with
 * its full `to` path (e.g. `/products/$slug`).
 */
function readGeneratedRoutePaths(): string[] {
  const src = readFileSync(
    resolve(process.cwd(), "src/routeTree.gen.ts"),
    "utf8",
  );
  const block = src.match(/interface FileRoutesByTo\s*\{([\s\S]*?)\n\}/);
  if (!block) throw new Error("FileRoutesByTo block not found in routeTree.gen.ts");
  const paths: string[] = [];
  for (const m of block[1].matchAll(/'([^']+)':/g)) {
    paths.push(m[1]);
  }
  return Array.from(new Set(paths));
}

const ROUTE_PATHS = readGeneratedRoutePaths();
const KNOWN_SET = new Set(KNOWN_PUBLIC_ROUTES);

/**
 * Paths the route tree contains that are intentionally served BY a different
 * mechanism than their own file route (e.g. /research, /about, /resources are
 * rendered through the /$ splat route, not a dedicated file). These ARE in
 * KNOWN_PUBLIC_ROUTES, so they pass without exception.
 *
 * Dynamic routes like /products/$slug expand to per-row entries at sitemap
 * generation time — the static "/products/$slug" path itself must be excluded.
 */
const DYNAMIC_PARAM_SUFFIX = /\$[A-Za-z_][A-Za-z0-9_]*$/;

describe("sitemap policy ↔ route-tree consistency", () => {
  it("every generated route is either excluded by policy or in KNOWN_PUBLIC_ROUTES", () => {
    const unclassified: string[] = [];
    for (const path of ROUTE_PATHS) {
      // Dynamic param leaf routes (e.g. /products/$slug) are expanded per-row
      // by the sitemap generator; the abstract path must be excluded.
      if (DYNAMIC_PARAM_SUFFIX.test(path)) {
        expect(
          isIndexable(path),
          `${path} is a dynamic param route and must NOT be indexable as-is (expanded per-row instead)`,
        ).toBe(false);
        continue;
      }

      const reason = exclusionReason(path);
      const inKnown = KNOWN_SET.has(path);

      if (reason && inKnown) {
        // Either signal alone is fine; both is contradictory.
        throw new Error(
          `${path} is in KNOWN_PUBLIC_ROUTES AND excluded by policy (${reason.kind}: ${reason.detail}). ` +
            `Remove it from one of: src/lib/sitemap-audit.functions.ts OR src/lib/sitemap-policy.ts`,
        );
      }
      if (!reason && !inKnown) {
        unclassified.push(path);
      }
    }

    expect(
      unclassified,
      `New route(s) detected with no sitemap policy decision.\n` +
        `Either add to KNOWN_PUBLIC_ROUTES in src/lib/sitemap-audit.functions.ts ` +
        `(to include in sitemap) or update src/lib/sitemap-policy.ts ` +
        `(TRANSACTIONAL_PREFIXES / NEVER_INDEX_EXACT / public/robots.txt) to exclude.\n` +
        `Unclassified: ${JSON.stringify(unclassified)}`,
    ).toEqual([]);
  });

  it("every KNOWN_PUBLIC_ROUTES path either has a real route file OR is served by the splat", () => {
    // Splat-served paths (e.g. /research, /about) won't appear in
    // FileRoutesByTo as their own entry — they match through '/$'. Confirm
    // the splat exists; if so, accept any KNOWN_PUBLIC_ROUTES path that has
    // no dedicated file as splat-served.
    const hasSplat = ROUTE_PATHS.includes("/$");
    expect(hasSplat, "expected /$ splat route to exist for fallback rendering").toBe(true);

    const routeSet = new Set(ROUTE_PATHS);
    for (const path of KNOWN_PUBLIC_ROUTES) {
      const hasOwnRoute = routeSet.has(path);
      // If there's no dedicated file, the splat must be the catch — that's
      // already verified above. Just sanity-check the path is well-formed.
      expect(path.startsWith("/"), `${path} must be absolute`).toBe(true);
      if (!hasOwnRoute) {
        // splat-served — fine, but log nothing; just ensure policy allows it.
        expect(
          isIndexable(path),
          `${path} is in KNOWN_PUBLIC_ROUTES but excluded by policy — fix one of them`,
        ).toBe(true);
      }
    }
  });
});
