/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as GoogleMerchantFeedDotxmlRouteImport } from './routes/google-merchant-feed[.]xml'
import { Route as GoogleAdsSafeFeedDotxmlRouteImport } from './routes/google-ads-safe-feed[.]xml'
import { Route as BingFeedDotxmlRouteImport } from './routes/bing-feed[.]xml'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as IndexnowKeyDottxtRouteImport } from './routes/$indexnowKey[.]txt'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products_.$slug'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCancelRouteImport } from './routes/payment.cancel'
import { Route as LandingPhlabsRouteImport } from './routes/landing.phlabs'
import { Route as LandingSlugRouteImport } from './routes/landing.$slug'
import { Route as CompareSlugRouteImport } from './routes/compare.$slug'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout.cancel'
import { Route as AdminMerchantFeedPreviewRouteImport } from './routes/admin.merchant-feed-preview'
import { Route as MarketingCompoundRouteImport } from './routes/_marketing.compound'
import { Route as ApiWebhooksWallidRouteImport } from './routes/api/webhooks/wallid'
import { Route as ApiPublicWebVitalsRouteImport } from './routes/api/public/web-vitals'
import { Route as ApiPublicSendMailRouteImport } from './routes/api/public/send-mail'
import { Route as ApiPublicPostPublishCheckRouteImport } from './routes/api/public/post-publish-check'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'
import { Route as ApiPublicErrorMonitorRouteImport } from './routes/api/public/error-monitor'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiPublicCoaPdfRouteImport } from './routes/api/public/coa-pdf'
import { Route as ApiPublicCacheConfigRouteImport } from './routes/api/public/cache-config'
import { Route as ApiPaymentsStatusRouteImport } from './routes/api/payments/status'
import { Route as ApiPaymentsCreateRouteImport } from './routes/api/payments/create'
import { Route as ApiPaymentsCancelRouteImport } from './routes/api/payments/cancel'
import { Route as ApiDsrProcessRouteImport } from './routes/api/dsr/process'
import { Route as ApiConfigPaymentsRouteImport } from './routes/api/config/payments'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksWatchdogRouteImport } from './routes/api/public/hooks/watchdog'
import { Route as ApiPublicHooksWallidReconcileRouteImport } from './routes/api/public/hooks/wallid-reconcile'
import { Route as ApiPublicHooksWallidMonitorRouteImport } from './routes/api/public/hooks/wallid-monitor'
import { Route as ApiPublicHooksWallidAlertsRouteImport } from './routes/api/public/hooks/wallid-alerts'
import { Route as ApiPublicHooksWallidRouteImport } from './routes/api/public/hooks/wallid'
import { Route as ApiPublicHooksTruelayerRouteImport } from './routes/api/public/hooks/truelayer'
import { Route as ApiPublicHooksToastAuditCleanupRouteImport } from './routes/api/public/hooks/toast-audit-cleanup'
import { Route as ApiPublicHooksSeoHealthDailyRouteImport } from './routes/api/public/hooks/seo-health-daily'
import { Route as ApiPublicHooksSecurityCleanupRouteImport } from './routes/api/public/hooks/security-cleanup'
import { Route as ApiPublicHooksPrerenderRecacheRouteImport } from './routes/api/public/hooks/prerender-recache'
import { Route as ApiPublicHooksMonitorProductUrlsRouteImport } from './routes/api/public/hooks/monitor-product-urls'
import { Route as ApiPublicHooksHealthCheckRouteImport } from './routes/api/public/hooks/health-check'
import { Route as ApiPublicHooksFenaProcessRetriesRouteImport } from './routes/api/public/hooks/fena-process-retries'
import { Route as ApiPublicHooksFenaRouteImport } from './routes/api/public/hooks/fena'
import { Route as ApiPublicHooksBacklinkWatcherRouteImport } from './routes/api/public/hooks/backlink-watcher'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleMerchantFeedDotxmlRoute =
  GoogleMerchantFeedDotxmlRouteImport.update({
    id: '/google-merchant-feed.xml',
    path: '/google-merchant-feed.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const GoogleAdsSafeFeedDotxmlRoute = GoogleAdsSafeFeedDotxmlRouteImport.update({
  id: '/google-ads-safe-feed.xml',
  path: '/google-ads-safe-feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BingFeedDotxmlRoute = BingFeedDotxmlRouteImport.update({
  id: '/bing-feed.xml',
  path: '/bing-feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexnowKeyDottxtRoute = IndexnowKeyDottxtRouteImport.update({
  id: '/$indexnowKey.txt',
  path: '/$indexnowKey.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products_/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelRoute = PaymentCancelRouteImport.update({
  id: '/payment/cancel',
  path: '/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPhlabsRoute = LandingPhlabsRouteImport.update({
  id: '/landing/phlabs',
  path: '/landing/phlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingSlugRoute = LandingSlugRouteImport.update({
  id: '/landing/$slug',
  path: '/landing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchantFeedPreviewRoute =
  AdminMerchantFeedPreviewRouteImport.update({
    id: '/admin/merchant-feed-preview',
    path: '/admin/merchant-feed-preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketingCompoundRoute = MarketingCompoundRouteImport.update({
  id: '/compound',
  path: '/compound',
  getParentRoute: () => MarketingRoute,
} as any)
const ApiWebhooksWallidRoute = ApiWebhooksWallidRouteImport.update({
  id: '/api/webhooks/wallid',
  path: '/api/webhooks/wallid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebVitalsRoute = ApiPublicWebVitalsRouteImport.update({
  id: '/api/public/web-vitals',
  path: '/api/public/web-vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendMailRoute = ApiPublicSendMailRouteImport.update({
  id: '/api/public/send-mail',
  path: '/api/public/send-mail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostPublishCheckRoute =
  ApiPublicPostPublishCheckRouteImport.update({
    id: '/api/public/post-publish-check',
    path: '/api/public/post-publish-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicErrorMonitorRoute = ApiPublicErrorMonitorRouteImport.update({
  id: '/api/public/error-monitor',
  path: '/api/public/error-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoaPdfRoute = ApiPublicCoaPdfRouteImport.update({
  id: '/api/public/coa-pdf',
  path: '/api/public/coa-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCacheConfigRoute = ApiPublicCacheConfigRouteImport.update({
  id: '/api/public/cache-config',
  path: '/api/public/cache-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsStatusRoute = ApiPaymentsStatusRouteImport.update({
  id: '/api/payments/status',
  path: '/api/payments/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCreateRoute = ApiPaymentsCreateRouteImport.update({
  id: '/api/payments/create',
  path: '/api/payments/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCancelRoute = ApiPaymentsCancelRouteImport.update({
  id: '/api/payments/cancel',
  path: '/api/payments/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDsrProcessRoute = ApiDsrProcessRouteImport.update({
  id: '/api/dsr/process',
  path: '/api/dsr/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigPaymentsRoute = ApiConfigPaymentsRouteImport.update({
  id: '/api/config/payments',
  path: '/api/config/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWatchdogRoute = ApiPublicHooksWatchdogRouteImport.update({
  id: '/api/public/hooks/watchdog',
  path: '/api/public/hooks/watchdog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWallidReconcileRoute =
  ApiPublicHooksWallidReconcileRouteImport.update({
    id: '/api/public/hooks/wallid-reconcile',
    path: '/api/public/hooks/wallid-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWallidMonitorRoute =
  ApiPublicHooksWallidMonitorRouteImport.update({
    id: '/api/public/hooks/wallid-monitor',
    path: '/api/public/hooks/wallid-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWallidAlertsRoute =
  ApiPublicHooksWallidAlertsRouteImport.update({
    id: '/api/public/hooks/wallid-alerts',
    path: '/api/public/hooks/wallid-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWallidRoute = ApiPublicHooksWallidRouteImport.update({
  id: '/api/public/hooks/wallid',
  path: '/api/public/hooks/wallid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTruelayerRoute = ApiPublicHooksTruelayerRouteImport.update({
  id: '/api/public/hooks/truelayer',
  path: '/api/public/hooks/truelayer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksToastAuditCleanupRoute =
  ApiPublicHooksToastAuditCleanupRouteImport.update({
    id: '/api/public/hooks/toast-audit-cleanup',
    path: '/api/public/hooks/toast-audit-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSeoHealthDailyRoute =
  ApiPublicHooksSeoHealthDailyRouteImport.update({
    id: '/api/public/hooks/seo-health-daily',
    path: '/api/public/hooks/seo-health-daily',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSecurityCleanupRoute =
  ApiPublicHooksSecurityCleanupRouteImport.update({
    id: '/api/public/hooks/security-cleanup',
    path: '/api/public/hooks/security-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPrerenderRecacheRoute =
  ApiPublicHooksPrerenderRecacheRouteImport.update({
    id: '/api/public/hooks/prerender-recache',
    path: '/api/public/hooks/prerender-recache',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMonitorProductUrlsRoute =
  ApiPublicHooksMonitorProductUrlsRouteImport.update({
    id: '/api/public/hooks/monitor-product-urls',
    path: '/api/public/hooks/monitor-product-urls',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksHealthCheckRoute =
  ApiPublicHooksHealthCheckRouteImport.update({
    id: '/api/public/hooks/health-check',
    path: '/api/public/hooks/health-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFenaProcessRetriesRoute =
  ApiPublicHooksFenaProcessRetriesRouteImport.update({
    id: '/api/public/hooks/fena-process-retries',
    path: '/api/public/hooks/fena-process-retries',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFenaRoute = ApiPublicHooksFenaRouteImport.update({
  id: '/api/public/hooks/fena',
  path: '/api/public/hooks/fena',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksBacklinkWatcherRoute =
  ApiPublicHooksBacklinkWatcherRouteImport.update({
    id: '/api/public/hooks/backlink-watcher',
    path: '/api/public/hooks/backlink-watcher',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$indexnowKey.txt': typeof IndexnowKeyDottxtRoute
  '/bing-feed.xml': typeof BingFeedDotxmlRoute
  '/google-ads-safe-feed.xml': typeof GoogleAdsSafeFeedDotxmlRoute
  '/google-merchant-feed.xml': typeof GoogleMerchantFeedDotxmlRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compound': typeof MarketingCompoundRoute
  '/admin/merchant-feed-preview': typeof AdminMerchantFeedPreviewRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/landing/phlabs': typeof LandingPhlabsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/config/payments': typeof ApiConfigPaymentsRoute
  '/api/dsr/process': typeof ApiDsrProcessRoute
  '/api/payments/cancel': typeof ApiPaymentsCancelRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/public/cache-config': typeof ApiPublicCacheConfigRoute
  '/api/public/coa-pdf': typeof ApiPublicCoaPdfRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/error-monitor': typeof ApiPublicErrorMonitorRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/post-publish-check': typeof ApiPublicPostPublishCheckRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/api/webhooks/wallid': typeof ApiWebhooksWallidRoute
  '/api/public/hooks/backlink-watcher': typeof ApiPublicHooksBacklinkWatcherRoute
  '/api/public/hooks/fena': typeof ApiPublicHooksFenaRoute
  '/api/public/hooks/fena-process-retries': typeof ApiPublicHooksFenaProcessRetriesRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/monitor-product-urls': typeof ApiPublicHooksMonitorProductUrlsRoute
  '/api/public/hooks/prerender-recache': typeof ApiPublicHooksPrerenderRecacheRoute
  '/api/public/hooks/security-cleanup': typeof ApiPublicHooksSecurityCleanupRoute
  '/api/public/hooks/seo-health-daily': typeof ApiPublicHooksSeoHealthDailyRoute
  '/api/public/hooks/toast-audit-cleanup': typeof ApiPublicHooksToastAuditCleanupRoute
  '/api/public/hooks/truelayer': typeof ApiPublicHooksTruelayerRoute
  '/api/public/hooks/wallid': typeof ApiPublicHooksWallidRoute
  '/api/public/hooks/wallid-alerts': typeof ApiPublicHooksWallidAlertsRoute
  '/api/public/hooks/wallid-monitor': typeof ApiPublicHooksWallidMonitorRoute
  '/api/public/hooks/wallid-reconcile': typeof ApiPublicHooksWallidReconcileRoute
  '/api/public/hooks/watchdog': typeof ApiPublicHooksWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$indexnowKey.txt': typeof IndexnowKeyDottxtRoute
  '/bing-feed.xml': typeof BingFeedDotxmlRoute
  '/google-ads-safe-feed.xml': typeof GoogleAdsSafeFeedDotxmlRoute
  '/google-merchant-feed.xml': typeof GoogleMerchantFeedDotxmlRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/compound': typeof MarketingCompoundRoute
  '/admin/merchant-feed-preview': typeof AdminMerchantFeedPreviewRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/landing/phlabs': typeof LandingPhlabsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/config/payments': typeof ApiConfigPaymentsRoute
  '/api/dsr/process': typeof ApiDsrProcessRoute
  '/api/payments/cancel': typeof ApiPaymentsCancelRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/public/cache-config': typeof ApiPublicCacheConfigRoute
  '/api/public/coa-pdf': typeof ApiPublicCoaPdfRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/error-monitor': typeof ApiPublicErrorMonitorRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/post-publish-check': typeof ApiPublicPostPublishCheckRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/api/webhooks/wallid': typeof ApiWebhooksWallidRoute
  '/api/public/hooks/backlink-watcher': typeof ApiPublicHooksBacklinkWatcherRoute
  '/api/public/hooks/fena': typeof ApiPublicHooksFenaRoute
  '/api/public/hooks/fena-process-retries': typeof ApiPublicHooksFenaProcessRetriesRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/monitor-product-urls': typeof ApiPublicHooksMonitorProductUrlsRoute
  '/api/public/hooks/prerender-recache': typeof ApiPublicHooksPrerenderRecacheRoute
  '/api/public/hooks/security-cleanup': typeof ApiPublicHooksSecurityCleanupRoute
  '/api/public/hooks/seo-health-daily': typeof ApiPublicHooksSeoHealthDailyRoute
  '/api/public/hooks/toast-audit-cleanup': typeof ApiPublicHooksToastAuditCleanupRoute
  '/api/public/hooks/truelayer': typeof ApiPublicHooksTruelayerRoute
  '/api/public/hooks/wallid': typeof ApiPublicHooksWallidRoute
  '/api/public/hooks/wallid-alerts': typeof ApiPublicHooksWallidAlertsRoute
  '/api/public/hooks/wallid-monitor': typeof ApiPublicHooksWallidMonitorRoute
  '/api/public/hooks/wallid-reconcile': typeof ApiPublicHooksWallidReconcileRoute
  '/api/public/hooks/watchdog': typeof ApiPublicHooksWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$indexnowKey.txt': typeof IndexnowKeyDottxtRoute
  '/_marketing': typeof MarketingRouteWithChildren
  '/bing-feed.xml': typeof BingFeedDotxmlRoute
  '/google-ads-safe-feed.xml': typeof GoogleAdsSafeFeedDotxmlRoute
  '/google-merchant-feed.xml': typeof GoogleMerchantFeedDotxmlRoute
  '/products': typeof ProductsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_marketing/compound': typeof MarketingCompoundRoute
  '/admin/merchant-feed-preview': typeof AdminMerchantFeedPreviewRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/landing/$slug': typeof LandingSlugRoute
  '/landing/phlabs': typeof LandingPhlabsRoute
  '/payment/cancel': typeof PaymentCancelRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/products_/$slug': typeof ProductsSlugRoute
  '/api/config/payments': typeof ApiConfigPaymentsRoute
  '/api/dsr/process': typeof ApiDsrProcessRoute
  '/api/payments/cancel': typeof ApiPaymentsCancelRoute
  '/api/payments/create': typeof ApiPaymentsCreateRoute
  '/api/payments/status': typeof ApiPaymentsStatusRoute
  '/api/public/cache-config': typeof ApiPublicCacheConfigRoute
  '/api/public/coa-pdf': typeof ApiPublicCoaPdfRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/api/public/error-monitor': typeof ApiPublicErrorMonitorRoute
  '/api/public/img': typeof ApiPublicImgRoute
  '/api/public/post-publish-check': typeof ApiPublicPostPublishCheckRoute
  '/api/public/send-mail': typeof ApiPublicSendMailRoute
  '/api/public/web-vitals': typeof ApiPublicWebVitalsRoute
  '/api/webhooks/wallid': typeof ApiWebhooksWallidRoute
  '/api/public/hooks/backlink-watcher': typeof ApiPublicHooksBacklinkWatcherRoute
  '/api/public/hooks/fena': typeof ApiPublicHooksFenaRoute
  '/api/public/hooks/fena-process-retries': typeof ApiPublicHooksFenaProcessRetriesRoute
  '/api/public/hooks/health-check': typeof ApiPublicHooksHealthCheckRoute
  '/api/public/hooks/monitor-product-urls': typeof ApiPublicHooksMonitorProductUrlsRoute
  '/api/public/hooks/prerender-recache': typeof ApiPublicHooksPrerenderRecacheRoute
  '/api/public/hooks/security-cleanup': typeof ApiPublicHooksSecurityCleanupRoute
  '/api/public/hooks/seo-health-daily': typeof ApiPublicHooksSeoHealthDailyRoute
  '/api/public/hooks/toast-audit-cleanup': typeof ApiPublicHooksToastAuditCleanupRoute
  '/api/public/hooks/truelayer': typeof ApiPublicHooksTruelayerRoute
  '/api/public/hooks/wallid': typeof ApiPublicHooksWallidRoute
  '/api/public/hooks/wallid-alerts': typeof ApiPublicHooksWallidAlertsRoute
  '/api/public/hooks/wallid-monitor': typeof ApiPublicHooksWallidMonitorRoute
  '/api/public/hooks/wallid-reconcile': typeof ApiPublicHooksWallidReconcileRoute
  '/api/public/hooks/watchdog': typeof ApiPublicHooksWatchdogRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$indexnowKey.txt'
    | '/bing-feed.xml'
    | '/google-ads-safe-feed.xml'
    | '/google-merchant-feed.xml'
    | '/products'
    | '/sitemap.xml'
    | '/compound'
    | '/admin/merchant-feed-preview'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/compare/$slug'
    | '/landing/$slug'
    | '/landing/phlabs'
    | '/payment/cancel'
    | '/payment/success'
    | '/products/$slug'
    | '/api/config/payments'
    | '/api/dsr/process'
    | '/api/payments/cancel'
    | '/api/payments/create'
    | '/api/payments/status'
    | '/api/public/cache-config'
    | '/api/public/coa-pdf'
    | '/api/public/csp-report'
    | '/api/public/error-monitor'
    | '/api/public/img'
    | '/api/public/post-publish-check'
    | '/api/public/send-mail'
    | '/api/public/web-vitals'
    | '/api/webhooks/wallid'
    | '/api/public/hooks/backlink-watcher'
    | '/api/public/hooks/fena'
    | '/api/public/hooks/fena-process-retries'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/monitor-product-urls'
    | '/api/public/hooks/prerender-recache'
    | '/api/public/hooks/security-cleanup'
    | '/api/public/hooks/seo-health-daily'
    | '/api/public/hooks/toast-audit-cleanup'
    | '/api/public/hooks/truelayer'
    | '/api/public/hooks/wallid'
    | '/api/public/hooks/wallid-alerts'
    | '/api/public/hooks/wallid-monitor'
    | '/api/public/hooks/wallid-reconcile'
    | '/api/public/hooks/watchdog'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/$indexnowKey.txt'
    | '/bing-feed.xml'
    | '/google-ads-safe-feed.xml'
    | '/google-merchant-feed.xml'
    | '/products'
    | '/sitemap.xml'
    | '/compound'
    | '/admin/merchant-feed-preview'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/compare/$slug'
    | '/landing/$slug'
    | '/landing/phlabs'
    | '/payment/cancel'
    | '/payment/success'
    | '/products/$slug'
    | '/api/config/payments'
    | '/api/dsr/process'
    | '/api/payments/cancel'
    | '/api/payments/create'
    | '/api/payments/status'
    | '/api/public/cache-config'
    | '/api/public/coa-pdf'
    | '/api/public/csp-report'
    | '/api/public/error-monitor'
    | '/api/public/img'
    | '/api/public/post-publish-check'
    | '/api/public/send-mail'
    | '/api/public/web-vitals'
    | '/api/webhooks/wallid'
    | '/api/public/hooks/backlink-watcher'
    | '/api/public/hooks/fena'
    | '/api/public/hooks/fena-process-retries'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/monitor-product-urls'
    | '/api/public/hooks/prerender-recache'
    | '/api/public/hooks/security-cleanup'
    | '/api/public/hooks/seo-health-daily'
    | '/api/public/hooks/toast-audit-cleanup'
    | '/api/public/hooks/truelayer'
    | '/api/public/hooks/wallid'
    | '/api/public/hooks/wallid-alerts'
    | '/api/public/hooks/wallid-monitor'
    | '/api/public/hooks/wallid-reconcile'
    | '/api/public/hooks/watchdog'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$indexnowKey.txt'
    | '/_marketing'
    | '/bing-feed.xml'
    | '/google-ads-safe-feed.xml'
    | '/google-merchant-feed.xml'
    | '/products'
    | '/sitemap.xml'
    | '/_marketing/compound'
    | '/admin/merchant-feed-preview'
    | '/checkout/cancel'
    | '/checkout/success'
    | '/compare/$slug'
    | '/landing/$slug'
    | '/landing/phlabs'
    | '/payment/cancel'
    | '/payment/success'
    | '/products_/$slug'
    | '/api/config/payments'
    | '/api/dsr/process'
    | '/api/payments/cancel'
    | '/api/payments/create'
    | '/api/payments/status'
    | '/api/public/cache-config'
    | '/api/public/coa-pdf'
    | '/api/public/csp-report'
    | '/api/public/error-monitor'
    | '/api/public/img'
    | '/api/public/post-publish-check'
    | '/api/public/send-mail'
    | '/api/public/web-vitals'
    | '/api/webhooks/wallid'
    | '/api/public/hooks/backlink-watcher'
    | '/api/public/hooks/fena'
    | '/api/public/hooks/fena-process-retries'
    | '/api/public/hooks/health-check'
    | '/api/public/hooks/monitor-product-urls'
    | '/api/public/hooks/prerender-recache'
    | '/api/public/hooks/security-cleanup'
    | '/api/public/hooks/seo-health-daily'
    | '/api/public/hooks/toast-audit-cleanup'
    | '/api/public/hooks/truelayer'
    | '/api/public/hooks/wallid'
    | '/api/public/hooks/wallid-alerts'
    | '/api/public/hooks/wallid-monitor'
    | '/api/public/hooks/wallid-reconcile'
    | '/api/public/hooks/watchdog'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  IndexnowKeyDottxtRoute: typeof IndexnowKeyDottxtRoute
  MarketingRoute: typeof MarketingRouteWithChildren
  BingFeedDotxmlRoute: typeof BingFeedDotxmlRoute
  GoogleAdsSafeFeedDotxmlRoute: typeof GoogleAdsSafeFeedDotxmlRoute
  GoogleMerchantFeedDotxmlRoute: typeof GoogleMerchantFeedDotxmlRoute
  ProductsRoute: typeof ProductsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminMerchantFeedPreviewRoute: typeof AdminMerchantFeedPreviewRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  CompareSlugRoute: typeof CompareSlugRoute
  LandingSlugRoute: typeof LandingSlugRoute
  LandingPhlabsRoute: typeof LandingPhlabsRoute
  PaymentCancelRoute: typeof PaymentCancelRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiConfigPaymentsRoute: typeof ApiConfigPaymentsRoute
  ApiDsrProcessRoute: typeof ApiDsrProcessRoute
  ApiPaymentsCancelRoute: typeof ApiPaymentsCancelRoute
  ApiPaymentsCreateRoute: typeof ApiPaymentsCreateRoute
  ApiPaymentsStatusRoute: typeof ApiPaymentsStatusRoute
  ApiPublicCacheConfigRoute: typeof ApiPublicCacheConfigRoute
  ApiPublicCoaPdfRoute: typeof ApiPublicCoaPdfRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  ApiPublicErrorMonitorRoute: typeof ApiPublicErrorMonitorRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
  ApiPublicPostPublishCheckRoute: typeof ApiPublicPostPublishCheckRoute
  ApiPublicSendMailRoute: typeof ApiPublicSendMailRoute
  ApiPublicWebVitalsRoute: typeof ApiPublicWebVitalsRoute
  ApiWebhooksWallidRoute: typeof ApiWebhooksWallidRoute
  ApiPublicHooksBacklinkWatcherRoute: typeof ApiPublicHooksBacklinkWatcherRoute
  ApiPublicHooksFenaRoute: typeof ApiPublicHooksFenaRoute
  ApiPublicHooksFenaProcessRetriesRoute: typeof ApiPublicHooksFenaProcessRetriesRoute
  ApiPublicHooksHealthCheckRoute: typeof ApiPublicHooksHealthCheckRoute
  ApiPublicHooksMonitorProductUrlsRoute: typeof ApiPublicHooksMonitorProductUrlsRoute
  ApiPublicHooksPrerenderRecacheRoute: typeof ApiPublicHooksPrerenderRecacheRoute
  ApiPublicHooksSecurityCleanupRoute: typeof ApiPublicHooksSecurityCleanupRoute
  ApiPublicHooksSeoHealthDailyRoute: typeof ApiPublicHooksSeoHealthDailyRoute
  ApiPublicHooksToastAuditCleanupRoute: typeof ApiPublicHooksToastAuditCleanupRoute
  ApiPublicHooksTruelayerRoute: typeof ApiPublicHooksTruelayerRoute
  ApiPublicHooksWallidRoute: typeof ApiPublicHooksWallidRoute
  ApiPublicHooksWallidAlertsRoute: typeof ApiPublicHooksWallidAlertsRoute
  ApiPublicHooksWallidMonitorRoute: typeof ApiPublicHooksWallidMonitorRoute
  ApiPublicHooksWallidReconcileRoute: typeof ApiPublicHooksWallidReconcileRoute
  ApiPublicHooksWatchdogRoute: typeof ApiPublicHooksWatchdogRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-merchant-feed.xml': {
      id: '/google-merchant-feed.xml'
      path: '/google-merchant-feed.xml'
      fullPath: '/google-merchant-feed.xml'
      preLoaderRoute: typeof GoogleMerchantFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-ads-safe-feed.xml': {
      id: '/google-ads-safe-feed.xml'
      path: '/google-ads-safe-feed.xml'
      fullPath: '/google-ads-safe-feed.xml'
      preLoaderRoute: typeof GoogleAdsSafeFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bing-feed.xml': {
      id: '/bing-feed.xml'
      path: '/bing-feed.xml'
      fullPath: '/bing-feed.xml'
      preLoaderRoute: typeof BingFeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$indexnowKey.txt': {
      id: '/$indexnowKey.txt'
      path: '/$indexnowKey.txt'
      fullPath: '/$indexnowKey.txt'
      preLoaderRoute: typeof IndexnowKeyDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products_/$slug': {
      id: '/products_/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancel': {
      id: '/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof PaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/phlabs': {
      id: '/landing/phlabs'
      path: '/landing/phlabs'
      fullPath: '/landing/phlabs'
      preLoaderRoute: typeof LandingPhlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing/$slug': {
      id: '/landing/$slug'
      path: '/landing/$slug'
      fullPath: '/landing/$slug'
      preLoaderRoute: typeof LandingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/merchant-feed-preview': {
      id: '/admin/merchant-feed-preview'
      path: '/admin/merchant-feed-preview'
      fullPath: '/admin/merchant-feed-preview'
      preLoaderRoute: typeof AdminMerchantFeedPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/compound': {
      id: '/_marketing/compound'
      path: '/compound'
      fullPath: '/compound'
      preLoaderRoute: typeof MarketingCompoundRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/api/webhooks/wallid': {
      id: '/api/webhooks/wallid'
      path: '/api/webhooks/wallid'
      fullPath: '/api/webhooks/wallid'
      preLoaderRoute: typeof ApiWebhooksWallidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/web-vitals': {
      id: '/api/public/web-vitals'
      path: '/api/public/web-vitals'
      fullPath: '/api/public/web-vitals'
      preLoaderRoute: typeof ApiPublicWebVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-mail': {
      id: '/api/public/send-mail'
      path: '/api/public/send-mail'
      fullPath: '/api/public/send-mail'
      preLoaderRoute: typeof ApiPublicSendMailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-publish-check': {
      id: '/api/public/post-publish-check'
      path: '/api/public/post-publish-check'
      fullPath: '/api/public/post-publish-check'
      preLoaderRoute: typeof ApiPublicPostPublishCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/error-monitor': {
      id: '/api/public/error-monitor'
      path: '/api/public/error-monitor'
      fullPath: '/api/public/error-monitor'
      preLoaderRoute: typeof ApiPublicErrorMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coa-pdf': {
      id: '/api/public/coa-pdf'
      path: '/api/public/coa-pdf'
      fullPath: '/api/public/coa-pdf'
      preLoaderRoute: typeof ApiPublicCoaPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cache-config': {
      id: '/api/public/cache-config'
      path: '/api/public/cache-config'
      fullPath: '/api/public/cache-config'
      preLoaderRoute: typeof ApiPublicCacheConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/status': {
      id: '/api/payments/status'
      path: '/api/payments/status'
      fullPath: '/api/payments/status'
      preLoaderRoute: typeof ApiPaymentsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/create': {
      id: '/api/payments/create'
      path: '/api/payments/create'
      fullPath: '/api/payments/create'
      preLoaderRoute: typeof ApiPaymentsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/cancel': {
      id: '/api/payments/cancel'
      path: '/api/payments/cancel'
      fullPath: '/api/payments/cancel'
      preLoaderRoute: typeof ApiPaymentsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dsr/process': {
      id: '/api/dsr/process'
      path: '/api/dsr/process'
      fullPath: '/api/dsr/process'
      preLoaderRoute: typeof ApiDsrProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/payments': {
      id: '/api/config/payments'
      path: '/api/config/payments'
      fullPath: '/api/config/payments'
      preLoaderRoute: typeof ApiConfigPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/watchdog': {
      id: '/api/public/hooks/watchdog'
      path: '/api/public/hooks/watchdog'
      fullPath: '/api/public/hooks/watchdog'
      preLoaderRoute: typeof ApiPublicHooksWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wallid-reconcile': {
      id: '/api/public/hooks/wallid-reconcile'
      path: '/api/public/hooks/wallid-reconcile'
      fullPath: '/api/public/hooks/wallid-reconcile'
      preLoaderRoute: typeof ApiPublicHooksWallidReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wallid-monitor': {
      id: '/api/public/hooks/wallid-monitor'
      path: '/api/public/hooks/wallid-monitor'
      fullPath: '/api/public/hooks/wallid-monitor'
      preLoaderRoute: typeof ApiPublicHooksWallidMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wallid-alerts': {
      id: '/api/public/hooks/wallid-alerts'
      path: '/api/public/hooks/wallid-alerts'
      fullPath: '/api/public/hooks/wallid-alerts'
      preLoaderRoute: typeof ApiPublicHooksWallidAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wallid': {
      id: '/api/public/hooks/wallid'
      path: '/api/public/hooks/wallid'
      fullPath: '/api/public/hooks/wallid'
      preLoaderRoute: typeof ApiPublicHooksWallidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/truelayer': {
      id: '/api/public/hooks/truelayer'
      path: '/api/public/hooks/truelayer'
      fullPath: '/api/public/hooks/truelayer'
      preLoaderRoute: typeof ApiPublicHooksTruelayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/toast-audit-cleanup': {
      id: '/api/public/hooks/toast-audit-cleanup'
      path: '/api/public/hooks/toast-audit-cleanup'
      fullPath: '/api/public/hooks/toast-audit-cleanup'
      preLoaderRoute: typeof ApiPublicHooksToastAuditCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/seo-health-daily': {
      id: '/api/public/hooks/seo-health-daily'
      path: '/api/public/hooks/seo-health-daily'
      fullPath: '/api/public/hooks/seo-health-daily'
      preLoaderRoute: typeof ApiPublicHooksSeoHealthDailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/security-cleanup': {
      id: '/api/public/hooks/security-cleanup'
      path: '/api/public/hooks/security-cleanup'
      fullPath: '/api/public/hooks/security-cleanup'
      preLoaderRoute: typeof ApiPublicHooksSecurityCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/prerender-recache': {
      id: '/api/public/hooks/prerender-recache'
      path: '/api/public/hooks/prerender-recache'
      fullPath: '/api/public/hooks/prerender-recache'
      preLoaderRoute: typeof ApiPublicHooksPrerenderRecacheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-product-urls': {
      id: '/api/public/hooks/monitor-product-urls'
      path: '/api/public/hooks/monitor-product-urls'
      fullPath: '/api/public/hooks/monitor-product-urls'
      preLoaderRoute: typeof ApiPublicHooksMonitorProductUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/health-check': {
      id: '/api/public/hooks/health-check'
      path: '/api/public/hooks/health-check'
      fullPath: '/api/public/hooks/health-check'
      preLoaderRoute: typeof ApiPublicHooksHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fena-process-retries': {
      id: '/api/public/hooks/fena-process-retries'
      path: '/api/public/hooks/fena-process-retries'
      fullPath: '/api/public/hooks/fena-process-retries'
      preLoaderRoute: typeof ApiPublicHooksFenaProcessRetriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fena': {
      id: '/api/public/hooks/fena'
      path: '/api/public/hooks/fena'
      fullPath: '/api/public/hooks/fena'
      preLoaderRoute: typeof ApiPublicHooksFenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/backlink-watcher': {
      id: '/api/public/hooks/backlink-watcher'
      path: '/api/public/hooks/backlink-watcher'
      fullPath: '/api/public/hooks/backlink-watcher'
      preLoaderRoute: typeof ApiPublicHooksBacklinkWatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketingRouteChildren {
  MarketingCompoundRoute: typeof MarketingCompoundRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingCompoundRoute: MarketingCompoundRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  IndexnowKeyDottxtRoute: IndexnowKeyDottxtRoute,
  MarketingRoute: MarketingRouteWithChildren,
  BingFeedDotxmlRoute: BingFeedDotxmlRoute,
  GoogleAdsSafeFeedDotxmlRoute: GoogleAdsSafeFeedDotxmlRoute,
  GoogleMerchantFeedDotxmlRoute: GoogleMerchantFeedDotxmlRoute,
  ProductsRoute: ProductsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminMerchantFeedPreviewRoute: AdminMerchantFeedPreviewRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  CompareSlugRoute: CompareSlugRoute,
  LandingSlugRoute: LandingSlugRoute,
  LandingPhlabsRoute: LandingPhlabsRoute,
  PaymentCancelRoute: PaymentCancelRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiConfigPaymentsRoute: ApiConfigPaymentsRoute,
  ApiDsrProcessRoute: ApiDsrProcessRoute,
  ApiPaymentsCancelRoute: ApiPaymentsCancelRoute,
  ApiPaymentsCreateRoute: ApiPaymentsCreateRoute,
  ApiPaymentsStatusRoute: ApiPaymentsStatusRoute,
  ApiPublicCacheConfigRoute: ApiPublicCacheConfigRoute,
  ApiPublicCoaPdfRoute: ApiPublicCoaPdfRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  ApiPublicErrorMonitorRoute: ApiPublicErrorMonitorRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
  ApiPublicPostPublishCheckRoute: ApiPublicPostPublishCheckRoute,
  ApiPublicSendMailRoute: ApiPublicSendMailRoute,
  ApiPublicWebVitalsRoute: ApiPublicWebVitalsRoute,
  ApiWebhooksWallidRoute: ApiWebhooksWallidRoute,
  ApiPublicHooksBacklinkWatcherRoute: ApiPublicHooksBacklinkWatcherRoute,
  ApiPublicHooksFenaRoute: ApiPublicHooksFenaRoute,
  ApiPublicHooksFenaProcessRetriesRoute: ApiPublicHooksFenaProcessRetriesRoute,
  ApiPublicHooksHealthCheckRoute: ApiPublicHooksHealthCheckRoute,
  ApiPublicHooksMonitorProductUrlsRoute: ApiPublicHooksMonitorProductUrlsRoute,
  ApiPublicHooksPrerenderRecacheRoute: ApiPublicHooksPrerenderRecacheRoute,
  ApiPublicHooksSecurityCleanupRoute: ApiPublicHooksSecurityCleanupRoute,
  ApiPublicHooksSeoHealthDailyRoute: ApiPublicHooksSeoHealthDailyRoute,
  ApiPublicHooksToastAuditCleanupRoute: ApiPublicHooksToastAuditCleanupRoute,
  ApiPublicHooksTruelayerRoute: ApiPublicHooksTruelayerRoute,
  ApiPublicHooksWallidRoute: ApiPublicHooksWallidRoute,
  ApiPublicHooksWallidAlertsRoute: ApiPublicHooksWallidAlertsRoute,
  ApiPublicHooksWallidMonitorRoute: ApiPublicHooksWallidMonitorRoute,
  ApiPublicHooksWallidReconcileRoute: ApiPublicHooksWallidReconcileRoute,
  ApiPublicHooksWatchdogRoute: ApiPublicHooksWatchdogRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
